// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StructuredAcceptance } from "./StructuredAcceptance";

export type Acceptance = { "type": "prose", text: string, } | { "type": "structured" } & StructuredAcceptance;
