// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Phase } from "./Phase";

export type AncestorSummary = { id: string, intent: string, phase: Phase, acceptance_summary: string, canonical_summary: string | null, progress: number, };
