// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FreezeProposal = { event_type: string, layer: string, item_json: string, reasoning: string, source_quote: string, };
