// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FreezeSession = { id: string, node_id: string, approved_items_json: string, current_layer: string, status: string, created_at: string | null, updated_at: string | null, };
