// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FreezeLayerCompleteEvent = { event_type: string, layer: string, next_layer: string | null, };
