// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Metric = { id: string, name: string, baseline: number | null, current: number | null, target: number, unit: string | null, };
