// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Phase } from "./Phase";
import type { Policy } from "./Policy";

export type NodeState = { state: Phase, progress: number, confidence: number, next_step: string, effective_policy: Policy, rollup_blockers: Array<string>, };
