// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Phase } from "./Phase";

export type Node = { id: string, intent: string, parent_id: string | null, phase: Phase, acceptance_json: string, local_policy_json: string | null, canonical_artifact_text: string | null, canonical_updated_by_run_id: string | null, next_step_cache: string | null, next_step_cache_for_run_id: string | null, created_at: string, updated_at: string, };
