// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Policy = { tokens_max: bigint | null, iterations_max: bigint | null, wallclock_max_s: bigint | null, allowed_tools: Array<string> | null, review_required: boolean | null, };
