// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RubricDimension = { id: string, dimension: string, score: number | null, scale: number, description: string | null, };
