// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Run = { id: string, node_id: string, type: string, status: string, runtime: string, input_snapshot_json: string | null, output_json: string | null, scratchpad_path: string | null, started_at: string | null, ended_at: string | null, created_at: string, };
