// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunInput } from "./RunInput";

export type RunDispatch = { run_id: string, input: RunInput, runtime: string, };
