// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RunEvent = { run_id: string, seq: bigint, event_type: string, data_text: string | null, };
