// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Acceptance } from "./Acceptance";
import type { AncestorSummary } from "./AncestorSummary";
import type { Policy } from "./Policy";

export type RunInput = { intent: string, acceptance: Acceptance, effective_policy: Policy, parent_context: Array<AncestorSummary>, node_docs: Array<string>, };
