// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Assertion } from "./Assertion";
import type { Metric } from "./Metric";
import type { RubricDimension } from "./RubricDimension";

export type RunOutput = { findings: string, concerns: Array<string>, confidence: number, needs_human_review: boolean, assertion_results: Array<Assertion>, metric_values: Array<Metric>, rubric_scores: Array<RubricDimension>, };
