// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Assertion } from "./Assertion";
import type { Metric } from "./Metric";
import type { RubricDimension } from "./RubricDimension";

export type StructuredAcceptance = { assertions: Array<Assertion>, metrics: Array<Metric>, rubric: Array<RubricDimension>, };
