// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunEvent } from "./RunEvent";
import type { RunTerminal } from "./RunTerminal";

export type WsDaemonMessage = { "kind": "event" } & RunEvent | { "kind": "terminal" } & RunTerminal;
